name = "find_ting"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
wisp = ">= 1.7.0 and < 2.0.0"
nakai = ">= 1.1.1 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
ids = ">= 0.14.0 and < 1.0.0"
mist = ">= 4.0.7 and < 5.0.0"
youid = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.1 and < 2.0.0"
